### ISSUE TITLE
can't drag between 2 grids with max row set

### ISSUE THREAD

**Issue by Justin99b** [gridstack/gridstack.js#1687]
## Subject of the issue
Widgets collide and bug over each other when hovering over another grid

## Your environment
Gridstack (the verison used on the official site) sorry dont know that one) (V4 if im not mistaken) <- 4.0.1
Chrome Version 89.0.4389.90 (64-Bit)

## Steps to reproduce
https://gridstackjs.com/#demo
when moving the item from top to bottom (i hope thats eough to reproduce)

## Expected behavior
Widget does not collide with others and just can correctly place back like in the previous v3 versions

## Actual behavior
When dragging one widget to another grid and then back (without releasing it) the widget will come nearly impossible to place back in the old grid and even collid or stack on to another object.
Its also happening when just dragging it into another grid.
You can also see the collision happening here https://gridstackjs.com/demo/advance.html
p.s im sorry if im not giving enough information.
if you need anything more please comment

**Comment by adumesny** [comment]
can you please provide a video because I'm not seeing your issue. you can also try using https://gridstackjs.com/demo/two.html or a modified version if you need 2 grids.

**Comment by Justin99b** [comment]
Actually i found out how to reproduce it


https://jsfiddle.net/rhq02fkL/23/
https://gyazo.com/de4abc0265c37760a7e8e8b71338b7ab

**Comment by adumesny** [comment]
should not see two drop shadow when #393 was fixed....

**Comment by Justin99b** [comment]
oh? Well im working on an inventory systemwith gridstack and use addGrid to dynamicly add grids. didnt know that this is the wrong way of doing it

**Comment by Justin99b** [comment]
Okay i've updated my example with your fixes named just to make sure its correct

https://jsfiddle.net/hfjr65qw/16/

**Comment by adumesny** [comment]
I know, but that is the clue bad things will happen!

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find lib useful!

**Comment by Justin99b** [comment]
If my projects works out and dont forget it i will donate you something 😄 

I checked out the master after you pushed. It seem to work way better than before

Im still having problems with the shadow tho. i have a 1x1 field to drop an item into.
besides the fact that 1x1 fields dont work at all in v3 and in v4 with your fix it works somewhat

Sometimes the drop shadows still wont dissapear. I will test this further and make sure to make a demo for you

Do you mean 4.0.3 or master when you say release?

**Comment by adumesny** [comment]
4.0.3

**Comment by adumesny** [comment]
a change in 4.0.3 broke my example (like yours).... will have to revisit this.
