### ISSUE TITLE
Overlapping widgets after dragging

### ISSUE THREAD

**Issue by athamsnajeeb1** [gridstack/gridstack.js#766]
The initial code is 
var options = {
                cellHeight: cellHeight,
                disableResize: true,
                disableDrag: false,
                handle: '.ibox-title',
                float : false ,
                
            };
            $('.grid-stack').gridstack(options);

And every grid-stack-item have settings data-gs-auto-position="1"  

when it dragging sometimes it comes over other widgets 

Can anyone help to solve this.

**Comment by radiolips** [comment]
Hey, @athamsnajeeb1 ! Hope you're doing well today.

Could you provide a jsfiddle or some other method for us to take a look at your code and whatever issue you're experiencing?

**Comment by erkather** [comment]
Hi,
I am also running into the same issue. I have created a jsfiddle[https://jsfiddle.net/cLdzzL8p/2/] where you can reproduce this issue.

Steps to reproduce:
1. Drag "Widget 3" a few inches left side.
2. Now "Widget 12" will be overlapped on "widget 1" and also few widgets will not be displayed. They are also displayed behind "Widget 12" similar to "Widget 1".

Thanks in Advance.

**Comment by brendonboshell** [comment]
It looks like this issue is resolved on the develop branch, so I assume it will come with the next release. In the meantime, you can cherry pick a38d78e on top of v0.3.0. This patch solved the problem for us.

**Comment by emonnet** [comment]
Just tried it and it solved this exact problem. I'm using the 0..3.0 release. Thanks !

**Comment by radiolips** [comment]
Great! I'll close this issue, but @athamsnajeeb1 please reopen it if this doesn't solve the original problem.

**Comment by erkather** [comment]
Thanks @brendonboshell . The version you have mentioned solved the issue.

**Comment by athamsnajeeb1** [comment]
thanks mate @erkather to help me by providing a jsfiddle, and Thanks @brendonboshell for helping to  solved the issue.
